# Generated by Django 2.0 on 2020-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='music',
            field=models.FileField(upload_to='static/media/upload_tracks/'),
        ),
    ]
